### ISSUE TITLE
README.md - Step 10 already changed

### ISSUE THREAD

**Issue by jenstrickland** [jasonlcrane/alexa-skill-mood-ring#1]
Under "AWS Lambda Setup" Step 10 changed. Now the options are: 
- create new role from template(s)
- create a custom role

I'm not sure what the correct option is, or I would do a pull request. I'm trying the template option and calling it "lambda_basic_execution" — if it works, I'll submit a PR.

**Comment by jasonlcrane** [comment]
Thanks @jenstrickland. I hope that worked for you. I updated the readme with what I think are the right instructions. When I wrote it originally, I already had the "lambda_basic_execution" role from a previous skill, which I overlooked. Thanks again!
